services:
  steamcmd:
    image: pz-steamcmd:custom
    container_name: steamcmd
    restart: unless-stopped
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
    volumes:
      - /root/gaming/mount/steamcmd_login_volume:/home/steam
      - /root/gaming/mount/steamcmd_volume:/home/steam/steamcmd
    # Run directly as the steam user (no su needed)
    user: steam
    command: /home/steam/Steam/servers/projectzomboid/start-server.sh -servername PZWestSide
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
